### ISSUE TITLE
Group-2: Git Workflow and Environment Setup for Project

### ISSUE THREAD

**Issue by project-delphi** [ccm-bioinfo/Camda24_resistance#9]
**Objective**:
Follow best practices for Git version control, consistent coding style, and Python environment management using Conda, ensuring seamless collaboration in a shared branch.

#### Tasks to Complete

1. **Branching and Committing to a Shared Branch**
   - [ ] Create a new feature branch from `group-2` using the naming convention: `feature/<feature-name>`.
   - [ ] Regularly commit changes to the feature branch with clear and descriptive commit messages.
   - [ ] Push commits to the shared remote branch.
   - [ ] Ensure all commits are related to the feature being developed (no unrelated changes).

2. **Consistent Variable Naming**
   - [ ] Agree on and follow a naming convention for variables (e.g., `snake_case` for Python).
   - [ ] Review and refactor existing code to maintain consistency.
   - [ ] Ensure consistent variable names across functions, classes, and files to improve code readability.

3. **GitHub Flow for Merging into Group-2 Branch**
   - [ ] Open a pull request (PR) from your feature branch to the `group-2` branch.
   - [ ] Ensure the PR description is clear, detailing the changes made.
   - [ ] Request code reviews from other team members.
   - [ ] Once approved, merge the feature branch into `group-2` using the GitHub Flow:
     1. Ensure the `group-2` branch is up-to-date with the main branch.
     2. Resolve any merge conflicts.
     3. After the merge, delete the feature branch to keep the repository clean.

4. **Use of `.gitignore`**
   - [ ] Create or update the `.gitignore` file to exclude unnecessary files, such as:
     - Conda environment files (e.g., `.conda`, `env/`).
     - Compiled Python files (e.g., `*.pyc`, `__pycache__/`).
     - Logs, temporary files, and dataset files.
   - [ ] Ensure the `.gitignore` is reviewed and properly configured for the project.

5. **Python Environment Setup with Conda**
   - [ ] Create a Conda environment for the project:
     ```bash
     conda create --name <env-name> python=3.8
     ```
   - [ ] Activate the environment:
     ```bash
     conda activate <env-name>
     ```
   - [ ] Ensure all dependencies are installed using a `requirements.txt` or `environment.yml` file.
   - [ ] Add environment management steps in the `README.md` for easy setup by other team members.
   - [ ] Add the Conda environment files (e.g., `environment.yml`) to the repository, excluding environment-specific files in `.gitignore`.

#### Example GitHub Flow

```bash
# Create and switch to a new feature branch
git checkout -b feature/new-feature

# Work on your changes and commit
git add .
git commit -m "Add new feature"

# Push changes to the shared remote feature branch
git push origin feature/new-feature

# After finishing, open a PR to the group-2 branch on GitHub

**Comment by project-delphi** [comment]
reset to clean modules with tested code.
